version: 2.1
jobs:
  build:
    working_directory: ~
    docker:
      - image: circleci/python:2.7.14
    steps:
      - checkout
      - run: python -m pip install --user -r requirements.txt
      - run: /home/circleci/.local/bin/coverage run -m unittest discover tests
      - run: /home/circleci/.local/bin/coverage report